export const badgeDescriptions = {
  "Aerial Wizard": "Improves alley-oop finishes and putbacks after offensive rebounds.",
  "Float Game": "Improves the success of floaters around the paint.",
  "Ghost Stepper": "Makes step-through layups and close shots after a pump fake more effective.",
  "Hook Specialist": "Improves scoring with hook shots from the post.",
  "Layup Mixmaster": "Improves fancy and acrobatic layup finishes.",
  "Paint Prodigy": "Helps players score quickly and efficiently inside the paint.",
  "Physical Finisher": "Improves contact finishes at the rim.",
  "Post Powerhouse": "Strengthens backdowns and dropsteps against post defenders.",
  "Post Spin Catalyst": "Improves post spins and drives while reducing strips.",
  Posterizer: "Raises the chance of completing dunks through or over defenders.",
  "Rise Up": "Improves standing dunks and posters from inside the paint.",
  "Arc Cadence": "Improves moving three-point shots, including pull-ups, hops, and spins.",
  Deadeye: "Reduces the penalty from late perimeter shot contests.",
  "Limitless Range": "Extends effective three-point shooting range.",
  "Mini Marksman": "Improves shots taken over taller defenders.",
  "Post Fade Phenom": "Improves post fades and post hop shots.",
  "Quick Trigger": "Improves jump shots taken without a dip.",
  "Set And Fire":
    "Applies a shooting boost to three-point attempts when the player’s feet are fully set.",
  "Smooth Operator": "Improves moving mid-range shots, including pull-ups, hops, and spins.",
  "Static Middy": "Boosts stand-still mid-range jump shots.",
  "Ankle Assassin": "Improves dribble moves that break down or cross up defenders.",
  "Bail Out": "Improves passes made from shots, layups, and double teams.",
  "Break Starter": "Improves long outlet passes after securing a defensive rebound.",
  Dimer: "Gives open shooters a boost after receiving a half-court pass.",
  "Handles For Days": "Reduces the energy cost of chaining dribble moves.",
  "Lightning Launch": "Speeds up perimeter launches and first steps.",
  Pace: "Raises sprint speed while controlling the ball.",
  "Strong Handle": "Improves strong crossover combinations against defenders.",
  Unpluckable: "Makes it harder for defenders to strip the ball.",
  "Versatile Visionary": "Improves quick reads and creative passes, including alley-oops.",
  "Ankle Braces": "Reduces the chance of being broken down by dribble moves.",
  Challenger: "Improves contests against perimeter jump shooters.",
  Glove: "Improves steals against ball handlers and strips on layups.",
  "High-Flying Denier": "Improves the speed, timing, and lift of block attempts.",
  "Immovable Enforcer": "Strengthens body defense against drives and direct finishes.",
  Interceptor: "Improves tipped passes and passing-lane steals.",
  "Off-Ball Pest": "Improves pressure and disruption while guarding off the ball.",
  "Paint Patroller": "Improves blocks and contests at the rim.",
  "Pick Dodger": "Helps defenders navigate through screens.",
  "Post Lockdown": "Improves post defense and strips against post moves.",
  Seatbelt: "Improves body-up defense and disrupts driving paths.",
  "Wall Up": "Improves hands-up contests while defending the paint.",
  "Boxout Boss": "Improves the strength and effectiveness of boxouts.",
  Breaker: "Improves the chance of breaking through an opponent’s boxout.",
  Crasher: "Improves tracking and securing offensive rebounds.",
  "Possession Closer": "Improves tracking and securing defensive rebounds.",
  "Sync Snatcher": "Adds a rebounding and vertical boost for perfectly timed jumps.",
  "Brick Wall": "Improves physical screens and resistance against strong drives.",
  Bruiser: "Drains opponent energy during physical contact.",
  Flash: "Speeds up off-ball movement during offensive and defensive transitions.",
  Pogostick: "Improves repeated jumps for rebounds, blocks, and passing lanes.",
  "Slippery Off-Ball": "Helps players move through traffic while trying to get open.",
  "Work Horse": "Improves speed and effort when pursuing loose balls.",
};
